// Code generated by mockery v2.25.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "microservice/shared/domain"
	dto "microservice/shared/dto"

	mock "github.com/stretchr/testify/mock"
)

// UserMysqlRepository is an autogenerated mock type for the UserMysqlRepository type
type UserMysqlRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: c, id
func (_m *UserMysqlRepository) Delete(c context.Context, id string) error {
	ret := _m.Called(c, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c, pagination
func (_m *UserMysqlRepository) Fetch(c context.Context, pagination *dto.Pagination) ([]*domain.User, error) {
	ret := _m.Called(c, pagination)

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.Pagination) ([]*domain.User, error)); ok {
		return rf(c, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.Pagination) []*domain.User); ok {
		r0 = rf(c, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.Pagination) error); ok {
		r1 = rf(c, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCondition provides a mock function with given fields: c, u
func (_m *UserMysqlRepository) GetByCondition(c context.Context, u domain.User) (domain.User, error) {
	ret := _m.Called(c, u)

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(c, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(c, u)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(c, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: c, id
func (_m *UserMysqlRepository) GetByID(c context.Context, id string) (domain.User, error) {
	ret := _m.Called(c, id)

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(c, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: c, u
func (_m *UserMysqlRepository) Store(c context.Context, u domain.User) (domain.User, error) {
	ret := _m.Called(c, u)

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(c, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(c, u)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(c, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, u
func (_m *UserMysqlRepository) Update(c context.Context, u domain.User) (domain.User, error) {
	ret := _m.Called(c, u)

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(c, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(c, u)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(c, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserMysqlRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserMysqlRepository creates a new instance of UserMysqlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserMysqlRepository(t mockConstructorTestingTNewUserMysqlRepository) *UserMysqlRepository {
	mock := &UserMysqlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
